export class FiledBase {
    constructor(public id?: number,
                public code?: string,
                public name?: string,
                public displayName?: string,
                public description?: string,
                public dataSourceType?: string,
                public dataSource?: string,
                public valueType?: string,
                public defaultValue?: string,
                public inputType?: string,
                public row?: number,
                public rowspan?: number,
                public col?: number,
                public colspan?: number,
                public primaryKey?: boolean,
                public nullable?: boolean,
                public creatable?: boolean,
                public updatable?: boolean,
                public sizeMin?: number,
                public sizeMax?: number,
                public valueMin?: string,
                public valueMax?: string,
                public validator?: string,
                public sort?: number,
                public formId?: number,
                public dictionaries?: {}[],
    ) {
    }
}
